# Generated by Django 4.1.1 on 2022-10-20 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_rename_id_flight_vuelo_vuelo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vuelo',
            old_name='vuelo',
            new_name='name',
        ),
    ]
