# Generated by Django 4.1.1 on 2022-10-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_rename_vuelo_vuelo_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vuelo',
            old_name='fligth_status',
            new_name='flight_status',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='name',
        ),
        migrations.AddField(
            model_name='vuelo',
            name='IATA',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='ICAO',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='airline',
            field=models.CharField(blank=True, choices=[('OTHER', 'OTHER'), ('AIRLINE', 'AIRLINE')], default='AIRLINE', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='airline_IATA',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='airline_ICAO',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='airline_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='flight',
            field=models.CharField(blank=True, choices=[('OTHER', 'OTHER'), ('FLIGHT', 'FLIGHT')], default='FLIGHT', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='flight_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
