# Generated by Django 4.1.1 on 2022-10-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_rename_fligth_status_vuelo_flight_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vuelo',
            old_name='IATA',
            new_name='name',
        ),
    ]
