# Generated by Django 4.1.1 on 2022-10-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_flight', models.CharField(max_length=255)),
                ('fligth_status', models.CharField(blank=True, choices=[('on time', 'on time'), ('delayed', 'delayed'), ('cancelled', 'cancelled'), ('diverted', 'diverted'), ('unknown', 'unknown'), ('shceduled', 'shceduled')], default='on time', max_length=100, null=True)),
            ],
        ),
    ]
