# Generated by Django 4.1.1 on 2022-10-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vuelo',
            old_name='id_flight',
            new_name='vuelo',
        ),
    ]
